In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

In [ ]:
#ching the version of numpy
import numpy as np
print(np.__version__)

In [ ]:
#--Creating the Array-----
import numpy as np
arr = np.array([1, 2, 3 , 4 , 5])
# print(arr)
# print(type(arr)) 
# print(arr.ndim)  #ndim is used to check the dimension of the array
# print(arr.shape) #shape is used to check the shape of the array
# print(arr.size) #size is used to check the size of the array
# print(arr. dtype) #dtype is used to check the data type of the array

# ----tuple to crate array---
arr = np.array((1, 2, 3, 4, 5))
print(arr) 

#----Dimension of Array---
#---0-D Array---
arr = np.array(42)
# print(arr)
# print(arr.ndim)

#---1-D Array---
arr = np.array([1, 2, 3, 4, 5])
# print(arr)
# print(arr.ndim)

#---2-D Array---
arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr)
# print(arr.ndim)

#---3-D Array---
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# print(arr)
# print(arr.ndim)

#---Higher Dimensional Array---
arr = np.array([1, 2, 3, 4], ndmin=5)
# print(arr)
# print('number of dimensions :', arr.ndim)

In [ ]:
#--------Array Indexing--------
import numpy as np
arr = np.array([1, 2, 3, 4])
# print(arr[0])     #accessing the first element
# print(arr[1])     #accessing the second element
# print(arr[2] + arr[3])   #accessing the third and fourth element and adding them
# print(arr[-1])       #accessing the last element
# print(arr[-3])       #accessing the third last element

#------2-D Array Indexing------
arr = np.array([[1, 2, 3, 4 , 5], [6, 7 , 8, 9, 10]])
# print(arr[0, 1])    #accessing the element at first row and second
# print(arr[1, 4])    #accessing the element at second row and fifth
# print(arr[1, -1])  #accessing the last element of second row
# print(arr[0, 3] + arr[1, 3])  #accessing the fourth element of first and second row and adding them

#------3-D Array Indexing------
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8,9], [10, 11, 12]]])
print(arr[0, 0, 1])  #accessing the second element of first array of first row
print(arr[1,1,2]) #accessing the third element of second array of second row
print(arr[0,1,0] + arr[1,0,2])

In [11]:
#------Numpy Array slicing----------------
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# print(arr[1:4]) #slicing elements from index 1 to 3 (not included)
# print(arr[4:])  #slicing elements from index 4 to end
# print(arr[:4])  #slicing elements from start to index 4 (not included)
# print(arr[-3:-1]) #slicing elements from index -3 to -1 (not included)
# print(arr[:])  #slicing all elements

#----used step while slicing-----
# print(arr[1:5:2])   #slicing elements from index 1 to 4 with step 2
# print(arr[::2])     #slicing all elements with step 2
# print(arr[1::2])    #slicing elements from index 1 to end with step 2
# print(arr[::-3])    #slicing all elements with step -3 (reverse order)
# print(arr[-1::-2])  #slicing all elements from last to first with step -2 (reverse order)

#------2-D Array Slicing------
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
# print(arr[1, 1:4])  #slicing elements from second row and index 1 to 3
# print(arr[0:2, 2])  #slicing elements from index 0 to 1 and third column
# print(arr[0:2, 1:4]) #slicing elements from index 0 to 1 and index 1 to 3
print(arr[2, 2:4]) #slicing elements from third row and index 2 to 3

[13 14]


In [1]:
#------data types in numpy array------
import numpy as np
arr = np.array([1, 2, 3, 4])
# print(arr.dtype)
arr = np.array(['apple', 'banana', 'cherry'])
# print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
# print(arr.dtype)

#------astype() to change data type------
arr = np.array([1, 2, 3, 0])
newarr = arr.astype('f')
boolarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)
print("boolean array", boolarr)
print(boolarr.dtype)


[1. 2. 3. 0.]
float32
boolean array [ True  True  True False]
bool


In [ ]:
#------copy vs view in numpy array------
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr2 = arr.copy() #copying the array
arr2[0] = 70
arr3 = arr.view() #viewing the array
arr[1] = 80
# print(arr2)
# print("view array ",arr3)
# print("original array" ,arr)
# print("id of original array", id(arr))
# print("id of copied array", id(arr2))

#---used base attribute to check if the array owns the data or not---
print(arr2.base) #None means that the array owns the data
print(arr3.base) #arr means that the array does not own the data


In [3]:
#------used the shape attribute to check the shape of the array------
import numpy as np
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
# print(arr.shape) #shape of the array
arr.shape = (3, 4) #changing the shape of the array
print(arr)
# print(arr.shape) #new shape of the array

#------used the reshape() method to give a new shape to an array------
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3) #reshaping the array to 4 rows and 3 columns
# print(newarr)
newarr = arr.reshape(2, 3, 2) #reshaping the array to 2 arrays of 3 rows and 2 columns
# print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#----itrating array usin for loop------
import numpy as np
arr = np.array([1, 2, 3, 4])
# for x in arr:
#     print(x)
#------iterating array nditer() function------
arr = np.array([[[1, 2, 3], [4, 5, 6]]])
for x in np.nditer(arr):
    print(x)

In [ ]:
#----------Numpy joining array------
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
# print(arr3)

#---along axis 2-d array-----
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate((arr1, arr2), axis=1)
# print(arr3)

#------stacking array------
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6]) 
arr3 = np.stack((arr1, arr2), axis=1)
# print(arr3)

#----hstack() function- row-----
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
# print(arr3)   


#----vstack() function- column-----
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])  
arr3 = np.vstack((arr1, arr2))
# print(arr3)

#----dstack() function- depth-----
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.dstack((arr1, arr2))
print(arr3)

In [ ]:
#-----Numpy splitting array------
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
# print(newarr)

#----2-D array spliting-----
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
newarr = np.array_split(arr, 3)
# print(newarr) 

#--------Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
# print(newarr[0])

#------Split the 2-D array into three 2-D arrays along columns----
newarr = np.array_split(arr, 3, axis=1)
newarr = np.hsplit(arr, 3)
# print(newarr[0])
print(newarr)


In [4]:
#-------Searching Array-------
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4, 6, 4])
# x = np.where(arr == 4)
# print(x)
#---Which means that the value 4 is present at index 3, 5, and 6

#-----Find the indexes where the values are even:-----
x = np.where(arr%2 == 0)
# print(x)

#---searchsorted() function----
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
# print(x)

#-----srarch from the right side of the array-----
x = np.searchsorted(arr, 7, side='right')
# print(x)

#----search multiple values in an array----
arr = np.array([1, 2, 3, 4, 5])
x = np.searchsorted(arr, [2, 4])
print(x)

[1 3]


In [ ]:
#-----sorting array------original array remains unchanged
import numpy as np
arr = np.array([3, 2, 0, 1])
# arr.sort()
# print(np.sort(arr))
# print(arr)

#-----sort array string-----
arr = np.array(['banana', 'cherry', 'apple'])
# print(np.sort(arr))

#-----sort--booolean array-----
arr = np.array([True, False, True])
# print(np.sort(arr))

#-----sort 2-D array-----
arr2 = np.array([[3, 2, 4], [5, 0, 1]])
# print(np.sort(arr))

#------filtering array------
arr3 = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr3[x]
# print(newarr)



In [17]:

#----Create a filter array that will return only values higher than 42:
import numpy as np
arr = np.array([41, 42, 43, 44])
#--create a empty list
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
# print(newarr)
# print(filter_arr)

#-----Creating Filter Directly From Array-----
filter_arr = arr > 42
dnewar = arr[filter_arr]
print(dnewar)

[43 44]
