In [ ]:
#---Exercises-01---creating a array-----
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# print(arr)

#---in-tupple---
arr = np.array((1,2,3,4,))
# print(arr)
# print(type(arr))

#---0-D-Array---
d_0arr = np.array(56)
# print(d_0arr)
# print(type(d_0arr))
# print(d_0arr.ndim) #check dimension

#----1-D----Array-----
d_1arr = np.array([1,5,6,7,4])
# print("1-D Array :",d_1arr)
# print(d_1arr.ndim)

#----2-D--Array-----
d_2arr = np.array([[4,5,5],[6,7,5]])
# print("2-D Array :",d_2arr)
# print(d_2arr.ndim)

#----3-D---Array-----------
d_3arr = np.array([[[1, 3, 4], [4, 5, 6]], [[8, 9, 0], [9, 4, 5]]])
print("3-D Array = ",d_3arr)
print(d_3arr.ndim)

#---Higher Dimensional Arrays---used--dnmin--
harr = np.array([1, 2, 3, 4, 5, 6, 6], ndmin=2)
print(harr)


In [ ]:
#----NUMPAY--ARRAY---INDEXING-------
import numpy as np
arr = np.array([1, 3, 5, 5])
# print(arr[3])

#---Access---2-D--array-----
arr2 = np.array([[1, 4, 5, 6], [4, 9, 0, 45]])
# print(arr2[0,1])  #--first-row-0--firs-numper
# print(arr2[1,3])

#---Access-3-D---array-----
arr3 = np.array([[[3, 5, 6, 6, 7], [8, 0, 8, 0, 9]], [[1, 2, 3, 4, 5], [6, 4, 3, 9, 0]]])
# print(arr3[1,1,2])

#----Negative---indexing----------
print(arr3[0,0, -2])
print(arr3[1,0,-3])
print(arr3[1,1, -3])



In [6]:
#--slice-----
arr = [1, 2, 34, 56, 9]
print("print 2 for end :",arr[2:])
print("print first to specified elemen :",arr[:3])
print("print last  elem :",arr[-1:])
print("print all elem :",arr[:-1])
print("print 3 to 1 :",arr[-3:-1])
print("print spefied elem :",arr[-3:])
print("print step 2 :",arr[::2])

print 2 for end : [34, 56, 9]
print first to specified elemen : [1, 2, 34]
print last  elem : [9]
print all elem : [1, 2, 34, 56]
print 3 to 1 : [34, 56]
print spefied elem : [34, 56, 9]
print step 2 : [1, 34, 9]


In [12]:
#----slicing--2-D---Array----------------
import numpy as np
arr2 = np.array([[1, 2, 3, 4, 5, 9], [34, 56, 89, 90, 34, 23]])
print(arr2[0,1:4])
print(arr2[0:3, 1])
print(arr2[1, 0:4])


[2 3 4]
[ 2 56]
[34 56 89 90]


In [21]:
#-------data--type---numpy------
import numpy as np
arr = np.array([1, 3, 4, 5, 5], dtype="S")
print(arr)
float = arr.astype('f')
print("After change the data type :",float)

arr = np.array([1, 2, 3, 0])
newarr = arr.astype('f')
# boolarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)
# print("boolean array", boolarr)
# print(boolarr.dtype)


[b'1' b'3' b'4' b'5' b'5']
After change the data type : [1. 3. 4. 5. 5.]
[1. 2. 3. 0.]
float32


In [45]:
#----Copy----and---view---numpy---arrray
import numpy as np
arr1 = np.array([[1, 3, 4, 5, 2, 1], [3, 4, 5, 6, 9, 9]])
arr2 = arr1.copy()
# arr2[0] = 20
# arr1[2] = 30
arr3 = arr1.view()

print(arr1)
print(arr2)
print(arr3)
print("id of original array :",id(arr1))
print("id of copy array :",id(arr2))

print("---------shape-----------------------")
print("check the shape of array :",arr1.shape)

#--changing---shape--of---array
# arr1.shape =(2,3)
# print(arr1.shape)

#------used the reshape() method to give a new shape to an array------
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,6) #reshaping the array to 4 rows and 3 columns
print(newarr)
newarr = arr.reshape(2, 3, 2) #reshaping the array to 2 arrays of 3 rows and 2 columns
# print(newarr)

[[1 3 4 5 2 1]
 [3 4 5 6 9 9]]
[[1 3 4 5 2 1]
 [3 4 5 6 9 9]]
[[1 3 4 5 2 1]
 [3 4 5 6 9 9]]
id of original array : 1423017552816
id of copy array : 1423014702000
---------shape-----------------------
check the shape of array : (2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
#-------iterating--for--loop----
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
# for x in arr:
    # print("arr :",x)

print("")
print("-----------2-D--array-------------")
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8,], [9, 10, 11,14]])
# for i in np.nditer(arr2):
    # print("2-d :",i)

print("")
print("-----------3-D-array-------------------")
arr3 = np.array([[[1, 2], [4, 5]], [[7, 8], [10, 11]]])
for i in np.nditer(arr3):
    print("3-D :",i)


-----------2-D--array-------------

-----------3-D-array-------------------
3-D : 1
3-D : 2
3-D : 4
3-D : 5
3-D : 7
3-D : 8
3-D : 10
3-D : 11


In [22]:
#----joining-----array------------
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
# arr3 = np.concatenate((arr1, arr2))
print(arr3)

#---along--axis--2-D---array----------
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr5 = np.array([[4, 6, 9], [10, 11, 12]])
arr6 = np.concatenate((arr4, arr5), axis=1)
print(arr6)

#-------stack---------
arr1 = np.array([1, 3, 4])
arr2 = np.array([5, 6, 8])
# stk = np.stack((arr1, arr3), axis=1)
arr3 = np.stack((arr1, arr2), axis=1)
print("stack :",arr3)

#------hstack--------
arr4 = np.hstack((arr1, arr2))
arr5 = np.vstack((arr1, arr2))
arr6 = np.dstack((arr1, arr2))
print("hstack :",arr4)
print("vstack :",arr5)
print("dstack :",arr6)

[1 2 3 4 5 6]
[[ 1  2  3  4  6  9]
 [ 4  5  6 10 11 12]]
stack : [[1 5]
 [3 6]
 [4 8]]
hstack : [1 3 4 5 6 8]
vstack : [[1 3 4]
 [5 6 8]]
dstack : [[[1 5]
  [3 6]
  [4 8]]]
